### ISSUE TITLE
Apps not showing Oppo

### ISSUE THREAD

**Issue by pijayfoot** [shmykelsa/AAAD#69] opened 2021-05-17 10:34 UTC
Hi
Have Oppo FInd X2 Pro, flagship ! but..... no apps are showing in AA menu :-(
Problem with all Oppo phones ? 

Any possible fix ?

thanks

**Comment by shmykelsa** [comment] 2021-05-17 14:05
Duplicate of #27

**Closed by shmykelsa** 2021-05-17 14:05 UTC

**Comment by totobranca** [comment] 2021-08-01 18:43
Oppo find x3 pro no apps with Android Auto
