### ISSUE TITLE
No AAAD app working on OnePlus

### ISSUE THREAD

**Issue by Gkeko** [shmykelsa/AAAD#249] opened 2023-05-16 18:32 UTC
Hello. I am using AAAD for almost 2 years. It was working perfectly on my old Xiaomi, but since i changed my phone to OnePlus Nord 2 5G, no AAAD app is working with my android auto. Tryed older android auto versions, but aint working. I did install Fermata with no problems, but my car aint detecting it.
Phone: Oneplus Nord 2 5g
Android: 12

**Comment by shmykelsa** [comment] 2023-05-16 19:19
Duplicate of #235

**Comment by shmykelsa** [comment] 2023-05-16 19:20
Check "Known issues" section of main page for more info.

**Closed** 2023-05-16 19:19 UTC
