### ISSUE TITLE
Oppo A53S - Apps Showing in AA, not starting when selected.

### ISSUE THREAD

**Issue by Zetrox2k** [shmykelsa/AAAD#111] opened 2021-08-10 00:00 UTC
Hi there.  

Installed AAAD and bought PRO, installed several apps, they show up on my car, but when selecting app it will not launch, instead it comes up with **No new messages during this drive.**

Using Oppo A53S with ColorOS 11 (Android 11) and AA 6.6.612534-release

![WhatsApp Image 2021-08-10 at 10 23 15](https://user-images.githubusercontent.com/22228670/128790331-61b9d39c-cba4-4476-b381-c817876d4cda.jpeg)

**Comment by shmykelsa** [comment] 2021-08-10 11:39
duplicate of #62

**Closed by shmykelsa** 2021-08-10 11:39 UTC
