### ISSUE TITLE
Not Working with my OPPO

### ISSUE THREAD

**Issue by moody2000** [shmykelsa/AAAD#119] opened 2021-09-04 05:32 UTC
Hello AAAD support,
I'd bought the pro-VR. and tried to follow the instructions, but nothing is shown on the Car screen.
I can see that an update is on its way, could I know the release date

**Comment by shmykelsa** [comment] 2021-09-05 08:55
Duplicate of #62

Please don't ask for ETAs

**Closed by shmykelsa** 2021-09-05 08:55 UTC
