### ISSUE TITLE
Paid version but still no pro feature

### ISSUE THREAD

**Issue by xabaras75** [shmykelsa/AAAD#28] opened 2021-05-04 07:30 UTC
I have bought the pro version bu no pro features on the app. How can I fix it? Which kind of info should I provide you to check it? My account on PayPal is antonio.xabaras@gmail.com.

**Comment by shmykelsa** [comment] 2021-05-04 07:30
Duplicate of #19

**Closed by shmykelsa** 2021-05-04 07:30 UTC
