### ISSUE TITLE
Note 10 plus - Android auto 6.5

### ISSUE THREAD

**Issue by Porcellino79** [shmykelsa/AAAD#105] opened 2021-07-14 07:32 UTC
Hello

I have a Note 10 Plus with Android auto 6.5.612134.
I have downloaded and installed AAAD 1.4 and downloaded AA Mirror. 
After that i dont know how make it work on my car. I cant see any AA Mirror icon when i plug my smartphone in car .
Anyone can help me?

**Comment by shmykelsa** [comment] 2021-07-14 08:26
Duplicate of #78

**Closed by shmykelsa** 2021-07-14 08:26 UTC
