### ISSUE TITLE
Can't install sceen2auto

### ISSUE THREAD

**Issue by pdario** [shmykelsa/AAAD#137] opened 2021-11-06 19:38 UTC
When I try to install sceen2auto, I go to the app site, select the latest version (3.6.1 now) and select to open it with AAAD. Then the phone says there's a problem with the package analysis.

What should I do?

**Comment by sFaxsy** [comment] 2021-11-06 20:42
Same issue

**Comment by cgmojoco** [comment] 2021-11-06 22:53
Same, parsing error when opening screen2auto via aaad

**Comment by cgmojoco** [comment] 2021-11-07 19:11
I tried:
Uninstall AAD.
Clear data/cache  AA  7.0.614134-release
 Installing AA 6.3.611344
Install AAD.
Upon opening AA 6.3.611344 I am asked to ugrade AA or it will not run.
Have not been successful in getting AAD to show up in AA.

**Comment by AleJaviSalva** [comment] 2021-11-07 22:51
Same issue

**Comment by shmykelsa** [comment] 2021-11-08 08:31
Duplicate of #107 

Thanks for the feedbacks. I'm looking into it.

**Closed by shmykelsa** 2021-11-08 08:31 UTC

**Comment by pdario** [comment] 2021-11-16 15:44
I see #107 is marked has closed, but I still can't install screen2auto.

Can you fix this?
