### ISSUE TITLE
AaaD no funciona en 	 Android Auto 6.4.611713

### ISSUE THREAD

**Issue by BoroB5** [shmykelsa/AAAD#76] opened 2021-05-20 11:01 UTC
Android auto se actualiza automaticamente a la version 6.4.611713 y ya no funciona la aplicacion AAAd.
Que no cunda el PANICO.
Primero hay que entrar en los ajustes de Google Play y desactivar actualizaciones automaticas, lo malo sera que debereis entrar de vez en cuando y actualizar manualmente las demas.
Desinstalar Android Auto, y yo lo he hecho desde esta pagina:
https://android-auto.uptodown.com/android/versions
instalais la ultima que funcionaba que es esta:	
Android Auto
6.3.611323-release, y Voila, otra vez como antes

**Comment by BoroB5** [comment] 2021-05-20 11:07
Se me olvidaba, por si acaso guardar la aplicacion, por si las moscas
	
Android Auto
6.3.611323-release

**Comment by maxxaya** [comment] 2021-05-31 22:02
When the fix is going to be issued? Is there any release date for 1.5 version?

**Comment by Salvertor** [comment] 2021-06-01 08:42
Pregúntaselo al autor

**Comment by Joe10s** [comment] 2021-06-01 18:37
Had the same problem. Downgrades to AA 6.3...

This helped.

https://youtu.be/3U112pZz6Dw

**Comment by highpowerxh** [comment] 2021-06-08 06:59
I was having this issue and I didn't get a chance to downgrade. However my AAWireless arrived a few days ago and surprisingly it is back working if I connect to AA wirelessly. Not sure it's AAWireless did some magic or wireless AA in general

**Comment by BoroB5** [comment] 2021-06-08 09:05
> Estaba teniendo este problema y no tuve la oportunidad de bajar de categoría. Sin embargo, mi AAWireless llegó hace unos días y, sorprendentemente, vuelve a funcionar si me conecto a AA de forma inalámbrica. No estoy seguro de que AAWireless haya hecho algo de magia o AA inalámbrico en general.

Que quieres decir con AAWireless, es algun aparato que has comprado?

**Comment by highpowerxh** [comment] 2021-06-08 15:01
> es esto lo que has comprado?
> https://www.indiegogo.com/projects/aawireless#/

yup

**Comment by BoroB5** [comment] 2021-06-08 17:33
Eso es un SI?

**Comment by highpowerxh** [comment] 2021-06-08 17:38
Not sure what you are asking. But if you are asking if I'm using https://www.indiegogo.com/projects/aawireless#/, yes, I am

**Comment by BoroB5** [comment] 2021-06-08 17:41
Indeed, that was asking you. But this product is out of stock, until October 21.
Works well for you, right?

**Comment by highpowerxh** [comment] 2021-06-08 19:30
This thing is working for me and I ordered last November, it's a crowdfunding project and they just started shipping a few month ago. But it does work for me flawlessly so far

**Comment by BoroB5** [comment] 2021-06-08 19:38
Ok, gracias.

**Comment by highpowerxh** [comment] 2021-06-08 20:03
They already have the device in production it's just matter of how many they can produce, I ordered that in November while it is in development and received that last week. They are pretty transparent on the rate of the production and how many they can ship. You need to read their [update ](https://www.indiegogo.com/projects/aawireless#/updates/all) and make your own judgement how long that will take

**Comment by BoroB5** [comment] 2021-06-08 20:06
Muchas Gracias , otra vez

**Comment by shmykelsa** [comment] 2021-06-16 09:11
Duplicate of #60

**Closed by shmykelsa** 2021-06-16 09:11 UTC
