### ISSUE TITLE
I can't anymore run android auto..

### ISSUE THREAD

**Issue by idjundje** [shmykelsa/AAAD#92] opened 2021-06-17 08:36 UTC
Hy,

From today, I can no longer run an android car if I don’t upgrade it.
I have ver. 6.3.611314 (see picture) and from today when I connect a cell phone (Samsung galaxy S20) to a car, I get a message that I need to update (see picture) it and wont run anymore., application don't want to run anymore in car.
I tried to reinstall the android car app but also it won't connect to the car, still same, I get message that update is available.
If I upgrade my android car it install ver. 6.5.612134 and in that version I no longer see third party applications installed.
So if someone can tell me if there is a solution to it and how I can fix it ..
thank you..

![appinfo](https://user-images.githubusercontent.com/76616420/122361358-76f7fc80-cf57-11eb-9fb6-3cd179c11fac.jpg) ![update](https://user-images.githubusercontent.com/76616420/122361371-78292980-cf57-11eb-9b2f-1e40a448afff.jpg)

**Comment by shmykelsa** [comment] 2021-06-17 08:37
Try with version 6.3.611334 instead of 6.3.611314.

**Comment by idjundje** [comment] 2021-06-17 08:47
Thank you, 

It work with this ver. 6.3.611334...

**Comment by shmykelsa** [comment] 2021-06-17 08:50
> It work with this ver. 6.3.611334...
So it's not asking for an update right now?

**Comment by idjundje** [comment] 2021-06-17 08:51
No, it is ok for now, it's not asking for an update for now..

**Comment by Beperoni** [comment] 2021-06-17 18:04
Had the same issue yesterday, upgrading to that version works but it seems as though it's temporary, I got this notification after doing the downgrade process that says updating AA will soon be required to continue using it. Would appear that the app phases out itself as new updates come out or something. Hope that AAAD finds a way to work on a newer version before we're pushed out again.

**Comment by idjundje** [comment] 2021-06-17 19:09
Or somehow to block AA for searching new updates..

**Comment by ripsee** [comment] 2021-06-18 02:10
I am having the same issue. Will try as advised to see if it resolves the issue.

Can we have this app working with latest versions as well.

Thanks

**Comment by Step-han** [comment] 2021-06-18 14:28
> Try with version 6.3.611334 instead of 6.3.611314.

Thanks, works for me!

**Comment by shmykelsa** [comment] 2021-06-18 16:51
> Can we have this app working with latest versions as well.

No.

Google applied some changes that proactively block AAAD apps and only solution is to run a version between 6.0 and 6.3. Android 9 and 10 will continue to work.

**Comment by Step-han** [comment] 2021-06-18 17:18
And what if version 6.3.611334 needs auto update? We can't use it anymore?

**Comment by shmykelsa** [comment] 2021-06-19 08:02
> And what if version 6.3.611334 needs auto update? We can't use it anymore?

That's correct

**Comment by emiralem** [comment] 2021-06-19 08:48
> > Can we have this app working with latest versions as well.
> 
> No.
> 
> Google applied some changes that proactively block AAAD apps and only solution is to run a version between 6.0 and 6.3. Android 9 and 10 will continue to work.

So, no chance for android 11, am I right?

**Comment by shmykelsa** [comment] 2021-06-19 12:23
> > > Can we have this app working with latest versions as well.
> > 
> > 
> > No.
> > Google applied some changes that proactively block AAAD apps and only solution is to run a version between 6.0 and 6.3. Android 9 and 10 will continue to work.
> 
> So, no chance for android 11, am I right?

Android 11 and 12

**Comment by xFaultx** [comment] 2021-06-19 14:45
Has anyone seen if spoofing your systems date does anything? If it's triggering in airplane mode (some on Reddit said it was) the three options i see are
1. It's based off the date that it breaks. Possibly, through rooting, just for that app alone the date can be spoofed. But you'd think we would have all broke on the same date, but possibly the issue.
2. The app dials home, and some server side issue is what broke it. But you'd think we would have all broke on the same date like above, but possibly the issue.
3. Maybe Google play services is what broke it, an external app. I have my apps set to not auto update, but i think google play services ignores this

**Comment by engrahafez** [comment] 2021-06-20 14:53
the phone push me to download last version of Android auto otherwise it take me out. I used the version no.    6.3.61133X but now android push me to install last update.

**Comment by munecito** [comment] 2021-06-20 21:20
I guess it is the end of the road. 

Google is prompting to update Android auto. I currently have version  6.3.611334  but now I got the dreaded message again.

**Comment by xFaultx** [comment] 2021-06-21 03:18
Rooted users! I may have found a solution. Using this app, along with AA AIO Tweaker (Google for the github) i was able to AA Mirror to work with the latest version, no issues! I'm really happy I found a solution

**Comment by filipvariciuc1** [comment] 2021-06-21 03:22
Same issue, I can't downgrade to any version without choosing to update or kicking me out. 

Anyone have a solution to prevent these updates?
I'm on Android 11 and just paid for pro today but nothing works since you are forced to update..

**Comment by filipvariciuc1** [comment] 2021-06-21 03:23
> Rooted users! I may have found a solution. Using this app, along with AA AIO Tweaker (Google for the github) i was able to AA Mirror to work with the latest version, no issues! I'm really happy I found a solution. Running off Android 11

I will try rooting hopefully it works

**Comment by filipvariciuc1** [comment] 2021-06-21 03:26
> Rooted users! I may have found a solution. Using this app, along with AA AIO Tweaker (Google for the github) i was able to AA Mirror to work with the latest version, no issues! I'm really happy I found a solution. Running off Android 11

After I download the AIO tweaker what do I do?

**Comment by xFaultx** [comment] 2021-06-21 05:04
> > Rooted users! I may have found a solution. Using this app, along with AA AIO Tweaker (Google for the github) i was able to AA Mirror to work with the latest version, no issues! I'm really happy I found a solution. Running off Android 11
> 
> After I download the AIO tweaker what do I do?

The only features I've tried are the custom apps and the tap limitations. I only was able to test this for a few minutes, but it worked with no issue

**Comment by idjundje** [comment] 2021-06-21 05:44
I tried to change date and time and I tried uninstall updates for google play services and google play (and then I disabled it) but same, still want update upp in ver. 6.3.611314 but in ver. 6.3.611334 is for now ok, but how long will it take I dont know...
It would be nice if someone could find out what needs to be blocked in the system.

**Comment by salman-mukhtar** [comment] 2021-06-21 06:03
> 6.3.611334

Version 6.3.611334 works now but it also says that AA needs to be updated soon to use new features.
I assume at some point google will force again to update AA and we will end up in similar issue.

**Comment by Arrages1960** [comment] 2021-06-25 10:49
Hi there :I am a Prom user. I have tried with version 6.3.611334 and works fine by now again. Lets see how long Google allow this without forcing a new AA update...

**Comment by engrahafez** [comment] 2021-06-25 18:29
That's right  version 6.3.611334 working now without updates 😃😃

**Comment by Halpph** [comment] 2021-06-27 09:52
Hi everyone, I had the same issue, then I followed the instructions you mentioned and eventually I ended up having android auto not working at all, when I plug it in my car it doesn't launch anymore, even with the official latest version...
Any chance you could help?

**Comment by JUVINATORO** [comment] 2021-07-05 07:48
Buenos días.
Lo que está claro es que hemos pagado para 
![image](https://user-images.githubusercontent.com/86950899/124436216-0aae3300-dd76-11eb-8b2b-76ebb82b0c76.png)
nada ... Samsung S11 no funciona ...
![image](https://user-images.githubusercontent.com/86950899/124436271-1699f500-dd76-11eb-87d5-ddd7cc776d09.png)

**Comment by JUVINATORO** [comment] 2021-07-05 07:48
![image](https://user-images.githubusercontent.com/86950899/124436394-303b3c80-dd76-11eb-8f32-59ae047cd6f4.png)

**Comment by JUVINATORO** [comment] 2021-07-05 07:49
![image](https://user-images.githubusercontent.com/86950899/124436498-51039200-dd76-11eb-9a19-778a3698bc26.png)

**Comment by rkachach** [comment] 2021-07-05 17:45
I run in the same issue (by having AA asking for upgrade) .. I'm running 6.3 on Android 10 (S10) and after a while the phone stopped working on my car. What I did as a workaround is to delete the AA app data and cache. With this basically it was as starting from scratch and I could have the app newly working (at least for a while before asking aging for upgrade..) .. hope it helps.

**Comment by youssef-elsayed** [comment] 2021-07-07 20:27
so clearing cash and app data on AA 6.3 worked? or at least gave you access to AA without been asked/forced to update?

**Comment by friederbluemle** [comment] 2021-07-07 20:48
[Copied over from #99 (now closed)]

Did anyone find out what's the last working version that does NOT force you to update? I'm also curious at what level this force update functionality is implemented. Is it only Android Auto, or does it reach deeper into the system? Maybe a combination of the OS, and the installed version of Google Play Services/etc.? Really scary how we gradually lose control over our devices - Android is turning more and more into Windows. 😟

**Comment by JUVINATORO** [comment] 2021-07-08 04:05
Hello. That's what I thought, it seems that instead of Android it's Windows, so many permissions, updates etc ...
Android is no longer the platform of years ago that was totally free, it is on its way to becoming Apple.

Best regards.



Joan Vidal.

________________________________
De: Frieder Bluemle ***@***.***>
Enviado: miércoles, 7 de julio de 2021 22:48
Para: shmykelsa/AAAD ***@***.***>
Cc: JUVINATORO ***@***.***>; Comment ***@***.***>
Asunto: Re: [shmykelsa/AAAD] I can't anymore run android auto.. (#92)


[Copied over from #99<https://github.com/shmykelsa/AAAD/issues/99> (now closed)]

Did anyone find out what's the last working version that does NOT force you to update? I'm also curious at what level this force update functionality is implemented. Is it only Android Auto, or does it reach deeper into the system? Maybe a combination of the OS, and the installed version of Google Play Services/etc.? Really scary how we gradually lose control over our devices - Android is turning more and more into Windows. 😟

**Comment by JUVINATORO** [comment] 2021-07-08 04:08
NO, it still does not work, I give up and I have several cracked App's, but with Android Auto it is different, it will be the mobile, it will be the car, I don't know, something is not compatible.


Best regards.

Joan Vidal.

________________________________
De: youssef-elsayed ***@***.***>
Enviado: miércoles, 7 de julio de 2021 22:27
Para: shmykelsa/AAAD ***@***.***>
Cc: JUVINATORO ***@***.***>; Comment ***@***.***>
Asunto: Re: [shmykelsa/AAAD] I can't anymore run android auto.. (#92)


so clearing cash and app data on AA 6.3 worked? or at least gave you access to AA without been asked/forced to update?

**Comment by rkachach** [comment] 2021-07-09 08:45
In my case my AA stopped working after several notification of upgrade requiered. To have it working newly I just cleared the data and cache. So it seems that the app is storing something to keep track of 'upgrade notifications' on the app data directory. It could have been worse if they store this somehow on our Google account then you couln'd even do what I did.

**Comment by engrahafez** [comment] 2021-07-27 16:42
AAAD stopped working for the version 6.3.611334

Please advise 

He asked me to update

**Comment by shmykelsa** [comment] 2021-07-28 11:01
Since this solution is now obsolete, please refer to [this ](https://github.com/shmykelsa/AAAD/issues/101)issue and to "Compatibility Issues" section on the main page

**Comment by JUVINATORO** [comment] 2021-07-28 11:34
Hello.  I found the solution on another website, I already told you that I didn't find it ethical to charge for some Apk's and not give support, just copy and paste ...Saludos.Joan Vidal.
-------- Mensaje original --------De: Gabriele Rizzo ***@***.***> Fecha: 28/7/21  13:02  (GMT+01:00) Para: shmykelsa/AAAD ***@***.***> Cc: JUVINATORO ***@***.***>, Comment ***@***.***> Asunto: Re: [shmykelsa/AAAD] I can't anymore run android auto.. (#92) 
Since this solution is now obsolete, please refer to this issue and to "Compatibility Issues" section on the main page

**Comment by Crewzj2489** [comment] 2021-07-28 15:15
So I was having issues bypassing the update screen on the latest 6.3. So I gave in and decided to update it to the latest version which is 6.6. I know alot of people was using Screen2auto but I was using Fermata Auto to use the web and watch YouTube videos on 6.3 because I never got the screen2auto to work. So after giving in to the update I tried Fermata and it actually works playing youtube videos and searching the web. I guess for now that's the only thing we can use for now until there's a work around because deleting data and cache didn't work for me. You can login to netflix using the web browser.

**Comment by Arrages1960** [comment] 2021-07-29 17:30
> Hello.  I found the solution on another website, I already told you that I didn't find it ethical to charge for some Apk's and not give support, just copy and paste ...Saludos.Joan Vidal. -------- Mensaje original --------De: Gabriele Rizzo ***@***.***> Fecha: 28/7/21 13:02 (GMT+01:00) Para: shmykelsa/AAAD ***@***.***> Cc: JUVINATORO ***@***.***>, Comment ***@***.***> Asunto: Re: [shmykelsa/AAAD] I can't anymore run android auto.. (#92) Since this solution is now obsolete, please refer to this issue and to "Compatibility Issues" section on the main page —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Hello Joan Vidal  !!! same thought here. Not ethical just sending a copy/paste link after paying for the app. Not support at all. Will you be so kind to send the web lsolution ink  to silver1960@hotmail.com ??? Best Regards from Spain.

**Comment by shmykelsa** [comment] 2023-02-27 19:28
Duplicate of #56

**Closed** 2023-02-27 19:28 UTC
